language: node_js
node_js:
  - '8'

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    on_success: change
    on_failure: always

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
  - stage: build
    script:
    - yarn
    - yarn build

  - stage: deploy
    script: yarn deploy
    after_script:
    - yarn alias
    - yarn clear-deployments
